name: .NET Core Desktop - Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v4

      # Zainstalowanie .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build aplikacji
      - name: Build solution
        run: dotnet build GenshinWishCounter1.5.sln --configuration Release

      # Tworzenie pliku ZIP
      - name: Create ZIP file
        run: |
          $outputPath = "${{ github.workspace }}\GenshinWishCounter_Release.zip"
          Compress-Archive -Path "${{ github.workspace }}\bin\Release\*" -DestinationPath $outputPath
        shell: pwsh

      # Utworzenie nowego release i upload ZIP
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "Automatyczny release z plikiem aplikacji"
          draft: false
          prerelease: false
          files: ${{ github.workspace }}\GenshinWishCounter_Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
